### General input stuff

In [1]:
import pandas as pd

In [40]:
sheet_id="1fbFp2IIFK4APGMAnl31kouZhYNsH0Ll7kbgxMH_J6B8"
# this is the key for the doc, hopefully does not change. Will edit as needed
url = f"https://docs.google.com/spreadsheets/d/1fbFp2IIFK4APGMAnl31kouZhYNsH0Ll7kbgxMH_J6B8/export?format=csv"
# copy the link up until edit, remove beyond that and add the export info
uma=pd.read_csv(url)
uma['Uma']=uma['Uma'].str.upper()
uma.head(5)

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
0,VIVLOS,81,51,86,156,-3,-2,-4,4,-5,-5,-5.81,0.637,67.73%,150.50,44.50
1,TAP DANCE CITY,89,55,88,170,11,6,0,6,-17,-17,1.14,0.609,59.52%,145.20,67.20
2,MIHONO BOURBON,86,54,87,160,1,3,-1,5,-4,-4,-1.15,0.602,68.44%,143.55,45.55
3,GOLD SHIP,88,55,88,170,11,5,0,6,-16,-16,0.00,0.600,59.52%,145.20,67.20
4,DARING HEART,82,52,84,165,6,-1,-3,2,-7,7,-2.38,0.596,56.00%,134.40,46.40

### the perfectly average uma

In [3]:
umasmol=uma.drop(columns = ['Uma', 'Height diff','Bust diff','Waist diff','Hips diff','Shortstack Score','Tallboard Score','TBHS',
                            'Hourglass Quotient','Oatmeal%','Donk Rating','Todo Index'])
umasmol.head()

   Bust  Waist  Hips  Height
0    81     51    86     156
1    89     55    88     170
2    86     54    87     160
3    88     55    88     170
4    82     52    84     165

In [4]:
explodegoal=umasmol.mean()
explodegoal.head()

Bust       82.570423
Waist      55.535211
Hips       81.873239
Height    158.521127
dtype: float64

In [5]:
explodemeans = [82.570423, 55.535211, 81.873239, 158.521127] 
# means from above
cols_to_check = ['Bust', 'Waist', 'Hips', 'Height']
# what columns we checking
distances = (uma[cols_to_check] - explodemeans).pow(2).sum(axis=1)
# distance from each
closest_row_index = distances.idxmin()
# index that binch
closest_row = uma.loc[closest_row_index]
# profit
print(f"The most average uma is {closest_row_index}:")
print(closest_row)

The most average uma is 71:
Uma                   Royce and Royce
Bust                               83
Waist                              56
Hips                               82
Height                            159
Height diff                         0
Bust diff                           0
Waist diff                          1
Hips diff                           0
Shortstack Score                    0
Tallboard Score                     0
TBHS                             1.22
Hourglass Quotient              0.473
Oatmeal%                       65.38%
Donk Rating                     106.6
Todo Index                        6.6
Name: 71, dtype: object

### Top for each of the categories

In [6]:
uma.nlargest(5, 'Bust')
# top 5 bustiest umas

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
27,Meisho Doto,99,61,89,164,5,16,6,7,-21,-21,11.24,0.541,76.51%,124.6,34.6
85,Hishi Akebono,99,64,88,180,21,16,9,6,-37,-37,12.50,0.461,60.22%,105.6,47.6
26,Super Creek,97,61,91,168,9,14,6,9,-23,-23,6.59,0.541,74.06%,136.5,54.5
100,Gentildonna,95,63,87,167,8,12,8,5,-20,-20,9.20,0.444,72.46%,104.4,20.4
122,Light Hello,95,65,89,157,-2,12,10,7,14,-14,6.74,0.415,94.38%,106.8,2.8

In [7]:
uma.nsmallest(5, 'Bust')
# top 5 flattest umas

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
125,Dream Journey,66,48,69,144,-15,-17,-7,-13,-32,-32,-4.35,0.406,53.64%,72.45,-57.55
113,Nishino Flower,67,48,70,135,-24,-16,-7,-12,-40,-40,-4.29,0.427,66.78%,77.00,-71.00
138,Stay Gold,67,49,68,142,-17,-16,-6,-14,-33,-33,-1.47,0.378,55.94%,64.60,-69.40
115,Narita Taishin,69,50,73,145,-14,-14,-5,-9,-28,-28,-5.48,0.420,61.04%,83.95,-44.05
126,Silence Suzuka,70,53,79,161,2,-13,-2,-3,-15,15,-11.39,0.406,55.11%,102.70,6.70

In [8]:
uma.nlargest(5, 'Waist')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
122,Light Hello,95,65,89,157,-2,12,10,7,14,-14,6.74,0.415,94.38%,106.8,2.8
85,Hishi Akebono,99,64,88,180,21,16,9,6,-37,-37,12.50,0.461,60.22%,105.6,47.6
92,Blast Onepiece,93,63,90,174,15,10,8,8,-25,-25,3.33,0.452,67.99%,121.5,51.5
100,Gentildonna,95,63,87,167,8,12,8,5,-20,-20,9.20,0.444,72.46%,104.4,20.4
131,Hishi Miracle,85,62,88,156,-3,2,7,6,5,-5,-3.41,0.395,88.90%,114.4,8.4

In [9]:
uma.nlargest(5, 'Hips')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
26,Super Creek,97,61,91,168,9,14,6,9,-23,-23,6.59,0.541,74.06%,136.5,54.5
13,Taiki Shuttle,94,59,90,172,13,11,4,8,-24,-24,4.44,0.559,65.01%,139.5,65.5
17,Mejiro Ramonu,87,57,90,165,6,4,2,8,-10,-10,-3.33,0.553,70.71%,148.5,60.5
92,Blast Onepiece,93,63,90,174,15,10,8,8,-25,-25,3.33,0.452,67.99%,121.5,51.5
27,Meisho Doto,99,61,89,164,5,16,6,7,-21,-21,11.24,0.541,76.51%,124.6,34.6

In [10]:
uma.nlargest(5, 'Height')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
85,Hishi Akebono,99,64,88,180,21,16,9,6,-37,-37,12.50,0.461,60.22%,105.6,47.6
92,Blast Onepiece,93,63,90,174,15,10,8,8,-25,-25,3.33,0.452,67.99%,121.5,51.5
13,Taiki Shuttle,94,59,90,172,13,11,4,8,-24,-24,4.44,0.559,65.01%,139.5,65.5
62,Biwa Hayahide,93,61,88,171,12,10,6,6,-22,-22,5.68,0.484,66.16%,118.8,42.8
136,Fenomeno,81,59,82,171,12,-2,4,0,-14,14,-1.22,0.381,56.06%,94.3,18.3

In [11]:
uma.nlargest(5, 'Height diff')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
85,Hishi Akebono,99,64,88,180,21,16,9,6,-37,-37,12.50,0.461,60.22%,105.6,47.6
92,Blast Onepiece,93,63,90,174,15,10,8,8,-25,-25,3.33,0.452,67.99%,121.5,51.5
13,Taiki Shuttle,94,59,90,172,13,11,4,8,-24,-24,4.44,0.559,65.01%,139.5,65.5
62,Biwa Hayahide,93,61,88,171,12,10,6,6,-22,-22,5.68,0.484,66.16%,118.8,42.8
136,Fenomeno,81,59,82,171,12,-2,4,0,-14,14,-1.22,0.381,56.06%,94.3,18.3

In [12]:
uma.nlargest(5, 'Bust diff')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
27,Meisho Doto,99,61,89,164,5,16,6,7,-21,-21,11.24,0.541,76.51%,124.6,34.6
85,Hishi Akebono,99,64,88,180,21,16,9,6,-37,-37,12.50,0.461,60.22%,105.6,47.6
26,Super Creek,97,61,91,168,9,14,6,9,-23,-23,6.59,0.541,74.06%,136.5,54.5
100,Gentildonna,95,63,87,167,8,12,8,5,-20,-20,9.20,0.444,72.46%,104.4,20.4
122,Light Hello,95,65,89,157,-2,12,10,7,14,-14,6.74,0.415,94.38%,106.8,2.8

In [13]:
uma.nlargest(5, 'Waist diff')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
122,Light Hello,95,65,89,157,-2,12,10,7,14,-14,6.74,0.415,94.38%,106.8,2.8
85,Hishi Akebono,99,64,88,180,21,16,9,6,-37,-37,12.50,0.461,60.22%,105.6,47.6
92,Blast Onepiece,93,63,90,174,15,10,8,8,-25,-25,3.33,0.452,67.99%,121.5,51.5
100,Gentildonna,95,63,87,167,8,12,8,5,-20,-20,9.20,0.444,72.46%,104.4,20.4
131,Hishi Miracle,85,62,88,156,-3,2,7,6,5,-5,-3.41,0.395,88.90%,114.4,8.4

In [14]:
uma.nlargest(5, 'Hips diff')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
26,Super Creek,97,61,91,168,9,14,6,9,-23,-23,6.59,0.541,74.06%,136.5,54.5
13,Taiki Shuttle,94,59,90,172,13,11,4,8,-24,-24,4.44,0.559,65.01%,139.5,65.5
17,Mejiro Ramonu,87,57,90,165,6,4,2,8,-10,-10,-3.33,0.553,70.71%,148.5,60.5
92,Blast Onepiece,93,63,90,174,15,10,8,8,-25,-25,3.33,0.452,67.99%,121.5,51.5
27,Meisho Doto,99,61,89,164,5,16,6,7,-21,-21,11.24,0.541,76.51%,124.6,34.6

In [15]:
uma.nlargest(5, 'Shortstack Score')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
57,Zenno Rob Roy,89,56,78,140,-19,6,1,-4,25,-25,14.10,0.491,87.69%,85.80,-52.20
14,Inari One,85,51,74,139,-20,2,-4,-8,22,-22,14.86,0.559,72.73%,85.10,-54.90
10,Belno Light,89,53,77,146,-13,6,-2,-5,19,-19,15.58,0.566,70.59%,92.40,-33.60
8,Marvelous Sunday,87,52,77,145,-14,4,-3,-5,18,-18,12.99,0.577,70.41%,96.25,-31.75
122,Light Hello,95,65,89,157,-2,12,10,7,14,-14,6.74,0.415,94.38%,106.80,2.80

In [16]:
uma.nlargest(5, 'Tallboard Score')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
99,Air Shakur,77,56,85,168,9,-6,1,3,-15,15,-9.41,0.446,59.12%,123.25,41.25
126,Silence Suzuka,70,53,79,161,2,-13,-2,-3,-15,15,-11.39,0.406,55.11%,102.70,6.70
136,Fenomeno,81,59,82,171,12,-2,4,0,-14,14,-1.22,0.381,56.06%,94.30,18.30
128,Vodka,76,55,78,165,6,-7,0,-4,-13,13,-2.56,0.400,52.37%,89.70,1.70
132,Tanino Gimlet,77,56,79,166,7,-6,1,-3,-13,13,-2.53,0.393,53.79%,90.85,4.85

In [17]:
uma.nlargest(5, 'TBHS')
# most top heavy

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
10,Belno Light,89,53,77,146,-13,6,-2,-5,19,-19,15.58,0.566,70.59%,92.40,-33.60
14,Inari One,85,51,74,139,-20,2,-4,-8,22,-22,14.86,0.559,72.73%,85.10,-54.90
57,Zenno Rob Roy,89,56,78,140,-19,6,1,-4,25,-25,14.10,0.491,87.69%,85.80,-52.20
8,Marvelous Sunday,87,52,77,145,-14,4,-3,-5,18,-18,12.99,0.577,70.41%,96.25,-31.75
85,Hishi Akebono,99,64,88,180,21,16,9,6,-37,-37,12.50,0.461,60.22%,105.60,47.60

In [18]:
uma.nsmallest(5, 'TBHS')
# most bottom heavy

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
95,Shinko Windy,77,57,88,152,-7,-6,2,6,-13,-13,-12.50,0.447,86.81%,136.40,22.40
126,Silence Suzuka,70,53,79,161,2,-13,-2,-3,-15,15,-11.39,0.406,55.11%,102.70,6.70
99,Air Shakur,77,56,85,168,9,-6,1,3,-15,15,-9.41,0.446,59.12%,123.25,41.25
67,Ikuno Dictus,75,53,82,163,4,-8,-2,0,-12,12,-8.54,0.481,56.81%,118.90,26.90
38,Grass Wonder,77,53,84,152,-7,-6,-2,2,-13,-13,-8.33,0.519,73.22%,130.20,16.20

In [19]:
uma.nlargest(5, 'Hourglass Quotient')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
0,Vivlos,81,51,86,156,-3,-2,-4,4,-5,-5,-5.81,0.637,67.73%,150.50,44.50
1,Tap Dance City,89,55,88,170,11,6,0,6,-17,-17,1.14,0.609,59.52%,145.20,67.20
2,Mihono Bourbon,86,54,87,160,1,3,-1,5,-4,-4,-1.15,0.602,68.44%,143.55,45.55
3,Gold Ship,88,55,88,170,11,5,0,6,-16,-16,0.00,0.600,59.52%,145.20,67.20
4,Daring Heart,82,52,84,165,6,-1,-3,2,-7,7,-2.38,0.596,56.00%,134.40,46.40

In [20]:
uma['Oatmeal%'] = uma['Oatmeal%'].str.replace('%', '').astype(float)
uma.nlargest(5, 'Oatmeal%')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
122,Light Hello,95,65,89,157,-2,12,10,7,14,-14,6.74,0.415,94.38,106.8,2.8
131,Hishi Miracle,85,62,88,156,-3,2,7,6,5,-5,-3.41,0.395,88.90,114.4,8.4
57,Zenno Rob Roy,89,56,78,140,-19,6,1,-4,25,-25,14.10,0.491,87.69,85.8,-52.2
95,Shinko Windy,77,57,88,152,-7,-6,2,6,-13,-13,-12.50,0.447,86.81,136.4,22.4
45,Marche Lorraine,90,59,89,157,-2,7,4,7,9,-9,1.12,0.517,83.77,133.5,29.5

In [21]:
uma.nlargest(5, 'Donk Rating')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
0,Vivlos,81,51,86,156,-3,-2,-4,4,-5,-5,-5.81,0.637,67.73,150.50,44.50
17,Mejiro Ramonu,87,57,90,165,6,4,2,8,-10,-10,-3.33,0.553,70.71,148.50,60.50
1,Tap Dance City,89,55,88,170,11,6,0,6,-17,-17,1.14,0.609,59.52,145.20,67.20
3,Gold Ship,88,55,88,170,11,5,0,6,-16,-16,0.00,0.600,59.52,145.20,67.20
2,Mihono Bourbon,86,54,87,160,1,3,-1,5,-4,-4,-1.15,0.602,68.44,143.55,45.55

In [22]:
uma.nlargest(5, 'Todo Index')

,Uma,Bust,Waist,Hips,Height,Height diff,Bust diff,Waist diff,Hips diff,Shortstack Score,Tallboard Score,TBHS,Hourglass Quotient,Oatmeal%,Donk Rating,Todo Index
1,Tap Dance City,89,55,88,170,11,6,0,6,-17,-17,1.14,0.609,59.52,145.2,67.2
3,Gold Ship,88,55,88,170,11,5,0,6,-16,-16,0.00,0.600,59.52,145.2,67.2
13,Taiki Shuttle,94,59,90,172,13,11,4,8,-24,-24,4.44,0.559,65.01,139.5,65.5
17,Mejiro Ramonu,87,57,90,165,6,4,2,8,-10,-10,-3.33,0.553,70.71,148.5,60.5
26,Super Creek,97,61,91,168,9,14,6,9,-23,-23,6.59,0.541,74.06,136.5,54.5

### Requests for specific uma

In [43]:
# when given an uma name, provides rankings in all categories.
indexuma=uma.set_index('Uma')
rankuma = indexuma.rank(ascending=False, method='min')
search_name = input("Enter the Uma you would like more information on: ").upper()
result = rankuma.loc[search_name]
print (result)

Enter the Uma you would like more information on:  special week

Bust                  83.0
Waist                 51.0
Hips                  77.0
Height                81.0
Height diff           81.0
Bust diff             83.0
Waist diff            51.0
Hips diff             77.0
Shortstack Score      30.0
Tallboard Score       33.0
TBHS                  75.0
Hourglass Quotient    97.0
Oatmeal%              72.0
Donk Rating           81.0
Todo Index            94.0
Name: SPECIAL WEEK, dtype: float64

### what if i wanna make my own uma?

In [26]:
# so this will be a lot more.... subjective? This will give general ratios that the secondary scores follow. 
bustratio=uma['Bust']/uma['Height']
bustratioM=bustratio.mean()
bustratioSTD=bustratio.std()
print(f"An uma's bust, on average, should be around: {bustratioM:.1%} of their height.")

An uma's bust, on average, should be around: 52.1% of their height.

In [27]:
waistratio=uma['Waist']/uma['Height']
waistratioM=waistratio.mean()
waistratioSTD=waistratio.std()
print(f"An uma's waist, on average, should be around: {waistratioM:.1%} of their height.")

An uma's waist, on average, should be around: 35.1% of their height.

In [28]:
hipsratio=uma['Hips']/uma['Height']
hipsratioM=hipsratio.mean()
hipsratioSTD=hipsratio.std()
print(f"An uma's hips, on average, should be around: {hipsratioM:.1%} of their height.")

An uma's hips, on average, should be around: 51.7% of their height.